### ISSUE TITLE
Fixed Joint parameters for use of IMU

### ISSUE THREAD

**Issue by robograffitti** [Field-Robotics-Japan/UnitySensorsArchive#17]
It is necessary to set a desired link for either of "Connected Body" or "Connected Articulation Body" parameter in Fixed Joint parameters.

However, the code looks like only aquisiting Rigidbody infomation like this:
https://github.com/arav-jp/UnitySensors/blob/main/Scripts/Runtime/IMU/IMU.cs#L71

And, Articulation Body class does not inheritate Rigid Body class, so I'm wondering where the program aquire Articulation Body info.

**Comment by RyodoTanaka** [comment]
I merged your modification PR.
This issue looks solved. I will close this.
