### ISSUE TITLE
Livox スクリプトが動作しない

### ISSUE THREAD

**Issue by RyodoTanaka** [Field-Robotics-Japan/UnitySensorsArchive#21]
@Autumn60 
Livox スクリプトを追加した状態で，PointCloud2 の中身が更新されません．
Addressables パッケージの設定がうまく行っていないんだと思いますが，設定方法がわかりません．
下記ブランチの UnitySensorsROSAssets の Scene ファイルに「Livox Mid70」として追加しました．

https://github.com/arav-jp/UnitySensorsROSAssets/tree/fix/livox-launch

上記 Scene にて設定等を変更していただきたいです．
また，ユーザーが設定する必要のない設定ファイル部分を隠していただけると嬉しいです．

1. 動作させるための手順を教えて頂く（設定値を修正して頂く）
2. ユーザーが見る必要のない設定をGUIからいじれないようにスクリプトを修正

上記をよろしくおねがいします．

**Comment by Autumn60** [comment]
![image](https://user-images.githubusercontent.com/37181352/197323033-3ac86227-4295-441f-a667-eee9a2d921b3.png)
まずは動作確認が出来たため、Addressablesの設定方法を載せておきます。

◎Addressables設定方法
対象CSVファイルのInspectorパネルでAddressableにチェックを入れる
→ファイルパス入力枠が現れるので適当なパス名を入力(これが、LivoxPublisher.csのInformationsのfile_pathに入力されているパス名と一致している必要があります)

**Comment by RyodoTanaka** [comment]
@Autumn60 
ありがとうございます．
教えていただいた方法でうまく行きました．

ROS側では Y軸方向にセンサ値が出てしまってるのですが，これは何か基準がありますか？
Unity：Z軸方向を計測
ROS：Y軸方向に計測結果が出る
![Screenshot from 2022-10-26 07-29-38](https://user-images.githubusercontent.com/8377208/197894273-545f6ca6-b000-4c3b-a57d-976f97e24011.png)

**Comment by Autumn60** [comment]
動作確認ありがとうございます。
軸方向についてはこちらのミスです。

(x, y, z) in Unity = (-y, z,x) in Rviz
（つまり、Unity内でZ方向を計測した結果がRviz上でX方向に出力される）

の認識で修正しようと考えていますが、これで問題ありませんか？

**Comment by RyodoTanaka** [comment]
@Autumn60 
問題ないです！

**Comment by Autumn60** [comment]
@RyodoTanaka 
#23 にて修正を出しました。確認よろしくお願いします。

**Comment by Autumn60** [comment]
https://github.com/Field-Robotics-Japan/UnitySensors/pull/23 で本Issueと結びつけるのを忘れていたため、Closeされていませんでした。上記PRで修正されたため、Closeします。
