### ISSUE TITLE
RotateLidarの向きについて

### ISSUE THREAD

**Issue by RyodoTanaka** [Field-Robotics-Japan/UnitySensorsArchive#6]
現状の実装では左手座標系をそのまま入力しているように思われる．
ROS側に渡す際には右手座標系に直す必要がある．

**Comment by qoopen0815** [comment]
ROS#に座標変換の実装があるので参考になります。

https://github.com/siemens/ros-sharp/blob/6e91309b2447c0919d3dabaa0650bb71e3e490dd/Unity3D/Assets/RosSharp/Scripts/Extensions/TransformExtensions.cs#L86-L114

**Comment by qoopen0815** [comment]
URDF Importer側にもありました。

https://github.com/Unity-Technologies/URDF-Importer/blob/e9859c4becda48194e153356afc0a802516b1488/com.unity.robotics.urdf-importer/Runtime/Extensions/BuiltInExtensions.cs#L103-L131

**Comment by RyodoTanaka** [comment]
#9 によって解決されました．
閉じます．
